// Central content registry for Fire Up Hibachi
// Drives sitemap, JSON-LD schema, and metadata for all location pages

export interface ContentEntry {
  slug: string;               // URL path like "/san-diego/la-jolla"
  title: string;              // Page <title> tag
  description: string;        // Meta description (max 160 chars)
  publishDate: string;        // ISO date: "2026-02-26"
  modifiedDate: string;       // ISO date: last edit
  city: string;               // City name for LocalBusiness schema
  county: string;             // e.g. "San Diego County"
  serviceArea: string;        // Neighborhood/area display name
  tags: string[];             // Keyword tags
  priority: number;           // Sitemap priority 0.0–1.0
  changeFrequency: 'daily' | 'weekly' | 'monthly';
}

export const contentRegistry: ContentEntry[] = [
  // ─── San Diego Hub ──────────────────────────────────────────────────────────
  {
    slug: '/san-diego',
    title: 'Hibachi Catering San Diego | Private Teppanyaki Chef | Fire Up Hibachi',
    description: 'Fire Up Hibachi brings premium private hibachi catering to San Diego. Chef Hernan — 14 years of teppanyaki experience — serves birthdays, weddings & corporate events. Free quote.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'San Diego',
    county: 'San Diego County',
    serviceArea: 'San Diego',
    tags: [
      'hibachi catering San Diego',
      'private hibachi chef San Diego',
      'teppanyaki catering San Diego',
      'mobile hibachi San Diego',
      'hibachi party San Diego',
      'backyard hibachi San Diego',
      'hibachi chef for hire San Diego',
    ],
    priority: 1.0,
    changeFrequency: 'weekly',
  },

  // ─── San Diego Neighborhoods ─────────────────────────────────────────────────
  {
    slug: '/san-diego/la-jolla',
    title: 'Hibachi Catering La Jolla | Private Teppanyaki Chef | Fire Up Hibachi',
    description: 'Luxury private hibachi catering in La Jolla, CA. Chef Hernan brings the full teppanyaki experience to your home, beach, or venue. Weddings, birthdays & private parties.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'La Jolla',
    county: 'San Diego County',
    serviceArea: 'La Jolla',
    tags: [
      'hibachi catering La Jolla',
      'private hibachi chef La Jolla',
      'teppanyaki La Jolla',
      'hibachi party La Jolla',
      'hibachi wedding La Jolla',
    ],
    priority: 0.9,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/chula-vista',
    title: 'Hibachi Catering Chula Vista | Private Teppanyaki | Fire Up Hibachi',
    description: 'Fire Up Hibachi serves Chula Vista with premium mobile hibachi catering. Birthdays, quinceañeras, corporate events & more. Book Chef Hernan for your next Chula Vista event.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'Chula Vista',
    county: 'San Diego County',
    serviceArea: 'Chula Vista',
    tags: [
      'hibachi catering Chula Vista',
      'private hibachi Chula Vista',
      'teppanyaki Chula Vista',
      'hibachi birthday party Chula Vista',
      'hibachi quinceañera Chula Vista',
    ],
    priority: 0.9,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/coronado',
    title: 'Hibachi Catering Coronado | Luxury Private Chef | Fire Up Hibachi',
    description: 'Premium private hibachi catering on Coronado Island. Fire Up Hibachi specializes in luxury events — weddings, private dining & corporate affairs on Coronado, CA.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'Coronado',
    county: 'San Diego County',
    serviceArea: 'Coronado',
    tags: [
      'hibachi catering Coronado',
      'private hibachi chef Coronado',
      'teppanyaki Coronado Island',
      'hibachi wedding Coronado',
      'luxury hibachi Coronado',
    ],
    priority: 0.85,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/encinitas',
    title: 'Hibachi Catering Encinitas | Private Teppanyaki Chef | Fire Up Hibachi',
    description: 'Private hibachi catering in Encinitas, CA. Backyard parties, beach events, weddings & birthdays. Chef Hernan delivers the full teppanyaki show to your Encinitas location.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'Encinitas',
    county: 'San Diego County',
    serviceArea: 'Encinitas',
    tags: [
      'hibachi catering Encinitas',
      'private hibachi Encinitas',
      'teppanyaki Encinitas',
      'backyard hibachi Encinitas',
      'hibachi beach party Encinitas',
    ],
    priority: 0.85,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/carlsbad',
    title: 'Hibachi Catering Carlsbad | Private Teppanyaki Chef | Fire Up Hibachi',
    description: 'Premium mobile hibachi catering in Carlsbad, CA. Corporate events, birthdays, weddings & private parties. Chef Hernan brings 14 years of teppanyaki expertise to Carlsbad.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'Carlsbad',
    county: 'San Diego County',
    serviceArea: 'Carlsbad',
    tags: [
      'hibachi catering Carlsbad',
      'private hibachi Carlsbad',
      'teppanyaki Carlsbad',
      'hibachi corporate event Carlsbad',
      'mobile hibachi Carlsbad',
    ],
    priority: 0.85,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/oceanside',
    title: 'Hibachi Catering Oceanside | Private Teppanyaki | Fire Up Hibachi',
    description: 'Mobile hibachi catering in Oceanside, CA. Family events, military appreciation parties, birthdays & weddings. Book Fire Up Hibachi for your Oceanside event today.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'Oceanside',
    county: 'San Diego County',
    serviceArea: 'Oceanside',
    tags: [
      'hibachi catering Oceanside',
      'private hibachi Oceanside',
      'teppanyaki Oceanside',
      'hibachi party Oceanside CA',
    ],
    priority: 0.8,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/escondido',
    title: 'Hibachi Catering Escondido | Private Teppanyaki Chef | Fire Up Hibachi',
    description: 'Private hibachi catering in Escondido, CA. Large backyard events, birthday parties, weddings & quinceañeras. Chef Hernan serves all of San Diego\'s inland communities.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'Escondido',
    county: 'San Diego County',
    serviceArea: 'Escondido',
    tags: [
      'hibachi catering Escondido',
      'private hibachi Escondido',
      'teppanyaki Escondido',
      'hibachi birthday Escondido',
    ],
    priority: 0.8,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/del-mar',
    title: 'Hibachi Catering Del Mar | Luxury Private Chef | Fire Up Hibachi',
    description: 'Upscale private hibachi catering in Del Mar, CA. Luxury events, private estate dinners, weddings & corporate affairs in Del Mar. Book Chef Hernan today.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'Del Mar',
    county: 'San Diego County',
    serviceArea: 'Del Mar',
    tags: [
      'hibachi catering Del Mar',
      'private hibachi chef Del Mar',
      'luxury hibachi Del Mar',
      'teppanyaki Del Mar CA',
    ],
    priority: 0.8,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/poway',
    title: 'Hibachi Catering Poway | Private Teppanyaki Chef | Fire Up Hibachi',
    description: 'Private hibachi catering in Poway, CA. Family birthdays, quinceañeras, backyard parties & more. Fire Up Hibachi brings the full teppanyaki show to your Poway home.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'Poway',
    county: 'San Diego County',
    serviceArea: 'Poway',
    tags: [
      'hibachi catering Poway',
      'private hibachi Poway',
      'teppanyaki Poway CA',
      'hibachi party Poway',
    ],
    priority: 0.75,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/el-cajon',
    title: 'Hibachi Catering El Cajon | Private Teppanyaki | Fire Up Hibachi',
    description: 'Mobile hibachi catering in El Cajon, CA. Birthday parties, family events, weddings & corporate catering. Chef Hernan serves East San Diego County.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'El Cajon',
    county: 'San Diego County',
    serviceArea: 'El Cajon',
    tags: [
      'hibachi catering El Cajon',
      'private hibachi El Cajon',
      'teppanyaki El Cajon',
      'hibachi birthday El Cajon',
    ],
    priority: 0.75,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/national-city',
    title: 'Hibachi Catering National City | Private Teppanyaki | Fire Up Hibachi',
    description: 'Private hibachi catering in National City, CA. Family celebrations, birthdays, quinceañeras & corporate events. Book Fire Up Hibachi for your National City event.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'National City',
    county: 'San Diego County',
    serviceArea: 'National City',
    tags: [
      'hibachi catering National City',
      'private hibachi National City',
      'teppanyaki National City CA',
    ],
    priority: 0.75,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/rancho-bernardo',
    title: 'Hibachi Catering Rancho Bernardo | Private Chef | Fire Up Hibachi',
    description: 'Private hibachi catering in Rancho Bernardo, CA. HOA events, private estate parties, corporate dinners & milestone celebrations. Book Chef Hernan today.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'Rancho Bernardo',
    county: 'San Diego County',
    serviceArea: 'Rancho Bernardo',
    tags: [
      'hibachi catering Rancho Bernardo',
      'private hibachi Rancho Bernardo',
      'teppanyaki Rancho Bernardo',
      'hibachi HOA event Rancho Bernardo',
    ],
    priority: 0.75,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/solana-beach',
    title: 'Hibachi Catering Solana Beach | Luxury Private Chef | Fire Up Hibachi',
    description: 'Luxury private hibachi catering in Solana Beach, CA. Upscale parties, weddings & private dinners steps from the Pacific. Book Fire Up Hibachi for your event.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'Solana Beach',
    county: 'San Diego County',
    serviceArea: 'Solana Beach',
    tags: [
      'hibachi catering Solana Beach',
      'private hibachi Solana Beach',
      'teppanyaki Solana Beach CA',
    ],
    priority: 0.75,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/mission-valley',
    title: 'Hibachi Catering Mission Valley | Corporate & Private Events | Fire Up Hibachi',
    description: 'Mobile hibachi catering in Mission Valley, San Diego. Corporate events, hotel parties, private dining & group celebrations. Book Chef Hernan for your Mission Valley event.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'San Diego',
    county: 'San Diego County',
    serviceArea: 'Mission Valley',
    tags: [
      'hibachi catering Mission Valley',
      'private hibachi Mission Valley San Diego',
      'teppanyaki Mission Valley',
      'corporate hibachi Mission Valley',
    ],
    priority: 0.75,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/santee',
    title: 'Hibachi Catering Santee | Private Teppanyaki Chef | Fire Up Hibachi',
    description: 'Mobile hibachi catering in Santee, CA. Birthday parties, family events, backyard cookouts & weddings. Chef Hernan serves all of East San Diego County.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'Santee',
    county: 'San Diego County',
    serviceArea: 'Santee',
    tags: [
      'hibachi catering Santee',
      'private hibachi Santee',
      'teppanyaki Santee CA',
      'hibachi party Santee',
    ],
    priority: 0.75,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/north-park',
    title: 'Hibachi Catering North Park | Private Teppanyaki Chef | Fire Up Hibachi',
    description: 'Private hibachi catering in North Park, San Diego. Trendy neighborhood dinners, private parties & corporate events. Book Fire Up Hibachi for your North Park event.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'San Diego',
    county: 'San Diego County',
    serviceArea: 'North Park',
    tags: [
      'hibachi catering North Park',
      'private hibachi North Park San Diego',
      'teppanyaki North Park',
      'hibachi dinner North Park',
    ],
    priority: 0.75,
    changeFrequency: 'weekly',
  },
  {
    slug: '/san-diego/point-loma',
    title: 'Hibachi Catering Point Loma | Private Teppanyaki Chef | Fire Up Hibachi',
    description: 'Private hibachi catering in Point Loma, San Diego. Military & naval events, upscale residential dinners, birthdays & weddings. Book Fire Up Hibachi today.',
    publishDate: '2026-02-26',
    modifiedDate: '2026-02-26',
    city: 'San Diego',
    county: 'San Diego County',
    serviceArea: 'Point Loma',
    tags: [
      'hibachi catering Point Loma',
      'private hibachi Point Loma',
      'teppanyaki Point Loma',
      'hibachi military event Point Loma',
    ],
    priority: 0.75,
    changeFrequency: 'weekly',
  },
];

// Helper: look up a single entry
export function getEntry(slug: string): ContentEntry | undefined {
  return contentRegistry.find(e => e.slug === slug);
}
